runtime: nodejs18

env: standard

# Automatic scaling configuration
automatic_scaling:
  max_instances: 2

# Optional environment variables for production
env_variables:
  NODE_ENV: "production"

# Entry point to start the app
entrypoint: node index.js

# Static file handlers (for serving static assets like CSS, JavaScript, images)
handlers:
  - url: /assets
    static_dir: assets

  - url: /css
    static_dir: css

  - url: /CV
    static_dir: CV

  - url: /.* 
    script: auto 
