runtime: nodejs18

env: standard

# Automatic scaling configuration
automatic_scaling:
  max_instances: 2

# Optional environment variables for production
env_variables:
  NODE_ENV: "production"

# Entry point to start the app
entrypoint: node index.js

# Static file handlers (for serving CSS, JavaScript, images, etc.)
handlers:
  - url: /assets
    static_dir: assets

  - url: /css
    static_dir: css

  - url: /.*
    script: auto  # Routes all other URLs to your Node.js app
